services:
  target:
    image: hello-realworld/java-spring-boot-jvm-java25:local
    container_name: hrw-target
    ports:
      - "8080:8080"
    environment:
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75"
      SPRING_THREADS_VIRTUAL_ENABLED: "false"
    cpus: "2.0"
    mem_limit: "1g"
