spring.autoconfigure.exclude=
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hrw}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:hrw}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:hrw}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false
spring.flyway.enabled=false
